# Generated by Django 6.0.6 on 2026-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
